### ISSUE TITLE
googstart_TTS runs on start up but google-assistant-demo not functional 

### ISSUE THREAD

**Issue by HarvsG** [jacksonsevendelta/GooglePi#4]
Running rpi in headless mode. The assistant runs at start up as evidenced by the "Assistant Ready" voice but does not function until login whereby it works until it quits at the end of the session.

It is fixed by the changes made in [this commit](https://github.com/jacksonsevendelta/GooglePi/pull/2/commits/8673737912e6f8fe402e6659102420a895d54680). The commit adds an `&` after the .bashrc line.

**Comment by shaunakg** [comment]
Yep. Merged the commit. It should work now.

Issue closed.
